DROP TABLE IF EXISTS "AUTO_PART";
CREATE TABLE "AUTO_PART" (
  ID       BIGINT      NOT NULL PRIMARY KEY,
  ARTICULE VARCHAR(30) NOT NULL,
  NAME     VARCHAR(50) NOT NULL,
  TYPE     BIGINT      NOT NULL,
  PRICE    DECIMAL     NOT NULL
);

CREATE TABLE "CART_ITEM" (
  ID_CART     BIGINT NOT NULL PRIMARY KEY,
  ID_AUTOPART BIGINT NOT NULL,
  COUNT       BIGINT
);

CREATE TABLE "CATALOGUE" (
  ID_AUTOPART BIGINT NOT NULL PRIMARY KEY,
  COUNT       BIGINT NOT NULL
);

CREATE TABLE "ORDER" (
  ID      BIGINT  NOT NULL PRIMARY KEY,
  ID_USER BIGINT  NOT NULL,
  TOTAL   DECIMAL NOT NULL,
  STATUS  BIGINT  NOT NULL
);

CREATE TABLE "ORDER_ITEM" (
  ID_ORDER BIGINT NOT NULL PRIMARY KEY,
  ID_AUTOPART BIGINT NOT NULL,
  COUNT BIGINT NOT NULL
);

CREATE TABLE "SHOPPING_CART" (
  ID BIGINT NOT NULL PRIMARY KEY,
  ID_USER BIGINT NOT NULL
);

CREATE TABLE "USER" (
  ID BIGINT NOT NULL PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  LOGIN VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(30) NOT NULL,
  ROLE BIGINT NOT NULL
);






