DROP TABLE IF EXISTS "AUTO_PART" CASCADE;
CREATE TABLE "AUTO_PART" (
  ID       SERIAL      NOT NULL PRIMARY KEY,
  ARTICULE VARCHAR(30) NOT NULL,
  NAME     VARCHAR(50) NOT NULL,
  TYPE     VARCHAR(50)      NOT NULL,
  PRICE    DECIMAL     NOT NULL
);

DROP TABLE IF EXISTS "CATALOGUE" CASCADE;
CREATE TABLE "CATALOGUE" (
  AUTOPART_ID BIGINT NOT NULL PRIMARY KEY REFERENCES "AUTO_PART"(ID),
  COUNT       INT NOT NULL
);

DROP TABLE IF EXISTS "USER" CASCADE;
CREATE TABLE "USER" (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  LOGIN VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(30) NOT NULL,
  ROLE VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS "ORDER" CASCADE;
CREATE TABLE "ORDER" (
  ID      SERIAL  NOT NULL PRIMARY KEY,
  USER_ID BIGINT  NOT NULL REFERENCES "USER"(ID),
  TOTAL   DECIMAL NOT NULL,
  STATUS  VARCHAR(50)  NOT NULL
);

DROP TABLE IF EXISTS "ORDER_ITEM" CASCADE;
CREATE TABLE "ORDER_ITEM" (
  ORDER_ID BIGINT NOT NULL PRIMARY KEY REFERENCES "ORDER"(ID),
  AUTOPART_ID BIGINT NOT NULL REFERENCES "AUTO_PART"(ID),
  COUNT INT NOT NULL
);

DROP TABLE IF EXISTS "SHOPPING_CART" CASCADE;
CREATE TABLE "SHOPPING_CART" (
  ID SERIAL NOT NULL PRIMARY KEY,
  USER_ID BIGINT NOT NULL REFERENCES "USER"(ID)
);

DROP TABLE IF EXISTS "CART_ITEM" CASCADE;
CREATE TABLE "CART_ITEM" (
  CART_ID     BIGINT NOT NULL REFERENCES "SHOPPING_CART"(ID),
  AUTOPART_ID BIGINT NOT NULL REFERENCES "AUTO_PART"(ID),
  COUNT       BIGINT NOT NULL,
  PRIMARY KEY (CART_ID,AUTOPART_ID)
);

SELECT * FROM "AUTO_PART";
INSERT INTO "AUTO_PART" VALUES (1,'123Q','ASDERRR','SUSPENSION',505.05);
INSERT INTO "AUTO_PART" VALUES (2,'124Q','ASDE','SUSPENSION',400);
UPDATE "AUTO_PART" SET type = 'SALON' WHERE id=2;
DELETE FROM "AUTO_PART" WHERE id=2;
SELECT * FROM "USER"





